### ISSUE TITLE
Seite Crawlen

### ISSUE THREAD

**Issue by crack00r** [twoDarkMessiah/py_moviecrawler#1]
Ist es mögliche die ganze Seite zu crawlen.
Alle Filme nur 1x in die Liste zu packen.
Ich hätte zb Interesse auf eine Vollstänige Liste aller Filme in 1080p - ohne 3D gedöns

In Zeiten von Amazon Cloud unlimited, könnte man ja alles dort saugen, und zu Amazon laden.

**Comment by twoDarkMessiah** [comment]
Hi crack00r,
das Script verfügt bereits über diverse Filtermechanismen. Diese sollen z.B. verhindern das kein Porn, 3D Releases oder Serien geladen werden.

Ein Crawlen der ganzen Seite würde wahrscheinlich ewig dauern, da würde auch kein Multihreading groß helfen. Soweit ich weiß wird Amazon Cloud Unlimited bald eingestellt, ansonsten wäre das mit passendem FUSE Provider (https://github.com/yadayada/acd_cli) eine super Lösung. 

Eine Alternative die ich evtl. auch noch implementieren werde, ist Filme basierend auf Listen von Trakt.tv oder Moviepilot.de zu laden.

---------------------------------
Amazon Drive mit unbegrenztem Speicher läuft aus:
http://www.zdnet.de/88300191/amazon-drive-mit-unbegrenztem-speicher-laeuft-aus/?inf_by=5940106f671db8bc3c8b46fd

**Comment by crack00r** [comment]
Naja, es gibt ja noch Google Drive unlimited :D

**Comment by twoDarkMessiah** [comment]
@crack00r 
Stimmt, ich habe aber gehört, dass zumindest die bei Ebay gekauften ACCs schnell gebannt werden;)

Ich habe im Update 0.4.0 eine Option hinzugefügt um alle Filme von W-H zu ziehen. Das Aufruf sollte etwa so aussehen: `"py_moviecrawler.py -o links.txt -t 8 -a"`
In meinem Test hat das Skript mit 8 Threads etwa 3-4 Minuten gebraucht und 4557 unique Ergebnisse zurückgeliefert. Ich hoffe du hast genügend OCH-Accs, das werden zig TB sein.

Falls du es wirklich mit GDrive unlimited nutzt, wäre es echt interessant zu hören wie es gelaufen ist.
